name: publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    if: github.repository_owner == 'megabyte6'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build --stacktrace
      - name: publish to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew modrinth modrinthSyncBody --stacktrace